// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCzflGO8fayqLAXCF9UUWtkR_rG846QY',
    appId: '1:272722041816:web:4a34cfccf3745fc87030ad',
    messagingSenderId: '272722041816',
    projectId: 'mynotes-osile-flutter-project',
    authDomain: 'mynotes-osile-flutter-project.firebaseapp.com',
    storageBucket: 'mynotes-osile-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD7Sh3tOhtjMu4zurlbblV6j6RZNp1V9Y',
    appId: '1:272722041816:android:a619b55e87cad8dc7030ad',
    messagingSenderId: '272722041816',
    projectId: 'mynotes-osile-flutter-project',
    storageBucket: 'mynotes-osile-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5dPXdUSAu93_3tVpT25u2N_hPjQfm3s',
    appId: '1:272722041816:ios:007c6ef8da5767d17030ad',
    messagingSenderId: '272722041816',
    projectId: 'mynotes-osile-flutter-project',
    storageBucket: 'mynotes-osile-flutter-project.appspot.com',
    iosClientId: '272722041816-f5s87hrf32rioindrb99e7chd0shdict.apps.googleusercontent.com',
    iosBundleId: 'ng.prideapps.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5dPXdUSAu93_3tVpT25u2N_hPjQfm3s',
    appId: '1:272722041816:ios:bf25bad99e89c3a47030ad',
    messagingSenderId: '272722041816',
    projectId: 'mynotes-osile-flutter-project',
    storageBucket: 'mynotes-osile-flutter-project.appspot.com',
    iosClientId: '272722041816-hpqa51nvdd7mus93naa1udlqs3d5284k.apps.googleusercontent.com',
    iosBundleId: 'ng.prideapps.mynotes.RunnerTests',
  );
}
